dist: xenial
before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-bibtex-extra texlive-bibtex-extra texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng texlive-publishers texlive-lang-czechslovak && sudo texhash"
script:
- mkdir .build
- REVID=${TRAVIS_COMMIT:0:7}
- BUILDCSTDATE=$(TZ="Europe/Prague" date +"%d-%h-%y, %H:%M:%S")
- sed -i -e "s/---REVISION\\\_ID---/$REVID/g" ./brochure-venturis.tex
- sed -i -e "s/---RELEASE\\\_ID---/$TRAVIS_TAG/g" ./brochure-venturis.tex  
- sed -i -e "s/---BUILDDATE---/$BUILDCSTDATE/g" ./brochure-venturis.tex  
- pdflatex -output-directory .build ./brochure-venturis.tex
- mv .build/brochure-venturis.pdf .build/manual.pdf
deploy:
  provider: releases
  api_key:
    secure: jPvgycNjXHMEjwKYBTF41eK0Dvy7Bz+nUWqShLkInk8E4LlDG7EBvg14HKuERHD1eojOmAOqPAoUVoN08DJ2qUVfyLKCRnxb7VL/q2t2v9lrklBsG9Oxd6W5q+wF7ceVqt8BKucy/XCGwjvAIKsjanuEWki/4hmK4l7HxYqzlaG3fsRDXCnayD2yxbSKA3mgtqw2sYsmcNqurDHquEGAKGrY7u1motoJ21WejVUwXKR6XVo00PUjgzKLdDVI4+q+cs+PW7PP33av7XMQmPvuaNVlLROHYRRitSiwowsc8aCwL7Qxxtu2TlQKlgEu6482jEkZFEu/8lXZrTUNPWIQUD6QjFGaOsdCY+mTDw3pDNapaMaQpO7vMNXsYlE2j72Uf9V1JkEM1S3XOvgUcJ5Yng+LXst8CeWlgG5k37MVD1HouGfz+5LbZHiOo240NlDCQ0gTHt8EKv4uvAqVGwDg4AdB4mOZhkIgMro8vtT/0ifxiJHzP4pWCCWCGgW23dhMmHrPgEjCF2JPMo2v7vtZMTz9H2iq0ZYhJdRc+JF9F6HwFBzjZcdBhciiZqTbwKBpuc2icdrvLuzOx9V5HV8h0Ud6E+D0ocK8sPmxkKiyBvoDFnTzLhFV9ksA7807Z+h7DcpH1F2sz1nWfZZ2poqkwrfYjqimU9YayjYfqvyao2U=
  file:
  - .build/manual.pdf
  skip_cleanup: true
  on:
    branch: master
    tags: true


