dist: xenial
before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-bibtex-extra texlive-bibtex-extra texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng texlive-publishers texlive-lang-czechslovak && sudo texhash"
script:
- mkdir .build
- REVID=${TRAVIS_COMMIT:0:7}
- BUILDCSTDATE=$(TZ="Europe/Prague" date +"%d-%h-%y, %H:%M:%S")
- sed -i -e "s/---REVISION\\\_ID---/$REVID/g" ./brochure-venturis.tex
- sed -i -e "s/---RELEASE\\\_ID---/$TRAVIS_TAG/g" ./brochure-venturis.tex  
- sed -i -e "s/---BUILDDATE---/$BUILDCSTDATE/g" ./brochure-venturis.tex  
- pdflatex -output-directory .build ./brochure-venturis.tex
- mv .build/brochure-venturis.pdf .build/manual.pdf
deploy:
  provider: releases
  api_key:
    secure: WvwUXi0se8+13GQG76nlkcy7/F2lfr5QeJ6ZTihoTpv1Drzn9YLsZLzSJ1Rt1wDVjDNdcQEaZ3UBnWYiACpKSVMD5X9aTVZ6We+mLgrPHYE8U9jFn5yDVmYqzEw67OyW7XHLPiGawlh4TFUbHL625IhatC7O4VoWhUsTTbwA5jVRc69sJu3M1p1n8kUwaSZFKDe5gm7hJTh3FP293hjTPV0QozfkPztZeVv4KDpq75jJizEOnuveRBSgZE7Kn6oOYobxSrNohbO3Hjvb3TI2pQgnY4tQizwHg2ejoSSqgg511/6wuUTKd+6JSnc+jP9v0KN5LpaWh/4dwFlvM8UXzLVncgUe9NM99PkTSJRK8ZbW4o+csKK8p6uQ3lG/WV80dXv01onXKBhtX+mjt/QQgMmzSQOVrPFlDwu/x7rZhtI7Ytgv8l7FaLDLqgem+zECJYlw1NoM4CU9d8Bm66fdevTN9O0A1lOs4iormLvIvjz8/bv0m5/TFbCzWCJBxWMZKcjN/J6QX37+7AE21w4OSxI/XbO3H1KH38lEsoXL5z9q6Aacqcw7u8qc5gYrB2BaAVsDIGoEGVdYRBKhpBNasjuwg0Y+/NvTmYl/ExcCYsoRJh7kMKbLYgqEKosLliLvWEyHlj6KtxcrXz3Vg56duBsdX4EOUovO7fFqGh/JEpk=
  file:
  - .build/manual.pdf
  skip_cleanup: true
  on:
    branch: master
    tags: true


